import { AxiosResponse } from "axios";
import { GetServerSideProps } from "next";
import Head from "next/head";
import qs from "qs";
import React from "react";
import Articles from "../../components/Articles";
import Categories from "../../components/Categories";
import { fetArticles, fetchCategories } from "../../http";
import { Article, Category, CollectionTypes, Pagination } from "../../types";

interface propsType {
  categories: Category[];
  articles: {
    items: Article[];
    pagination: Pagination;
  };
}

const category = ({ categories, articles }: propsType) => {
  return (
    <>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Categories categories={categories} />
        <Articles articles={articles.items} />
      </div>
    </>
  );
};

export default category;

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const options = {
    populate: ["author.avatar"],
    sort: ["id:desc"],
    filters: {
      category: {
        slug: query.categorySlug,
      },
    },
  };
  const queryString = qs.stringify(options);

  const { data: category }: AxiosResponse<CollectionTypes<Category[]>> =
    await fetchCategories();

  const { data: articles }: AxiosResponse<CollectionTypes<Article[]>> =
    await fetArticles(queryString);
  return {
    props: {
      categories: category.data,
      articles: {
        items: articles.data,
        pagination: articles.meta.pagination,
      },
    },
  };
};
