import { AxiosResponse } from "axios";
import { GetServerSideProps } from "next";
import Head from "next/head";
import Image from "next/image";
import qs from "qs";
import React from "react";
import { fetchArticles } from "../../http";
import { CollectionTypes, Article } from "../../types";
import { formatDate } from "../../utils/index";

interface propsType {
  singleArticle: Article;
}
const articleSlug = ({ singleArticle }: propsType) => {
  const { title, body } = singleArticle.attributes;
  console.log(singleArticle.attributes);
  return (
    <>
      <Head>
        <title>Next Blog | Article</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row mt-5">
        <div className="col-md-8">
          <h4>{title}</h4>
          <div className="py-2">
            <Image
              src={`http://localhost:1337${singleArticle.attributes.author.data.attributes.avatar.data.attributes.formats.thumbnail.url}`}
              alt="avatar"
              height={30}
              width={30}
              className="rounded"
            />
            <span className="mx-2 fw-bold">
              {singleArticle.attributes.author.data.attributes.firstName}{" "}
              {singleArticle.attributes.author.data.attributes.lastName}
            </span>
            <span className="article-created">
              {formatDate(singleArticle.attributes.createdAt)}
            </span>
          </div>
          <div className="mt-4">
            {singleArticle.attributes.image?.data && (
              <Image
                src={`http://localhost:1337${singleArticle.attributes.image?.data?.attributes?.url}`}
                alt="body image"
                className="img-fluid"
                height={350}
                width={800}
              />
            )}
            <p className="pt-3">{body}</p>
          </div>
        </div>
        <div className="col-md-4">hello</div>
      </div>
    </>
  );
};

export default articleSlug;

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const options = {
    populate: ["image", "author.avatar"],
    filters: {
      slug: {
        $eq: query.articleSlug,
      },
    },
  };
  const queryString = qs.stringify(options);

  const { data: article }: AxiosResponse<CollectionTypes<Article[]>> =
    await fetchArticles(queryString);
  return {
    props: {
      singleArticle: article.data[0],
    },
  };
};
