import Head from "next/head";
import React from "react";

const Contact = () => {
  return (
    <section className="mx-auto text-center">
      <Head>
        <title>Next Blog | Contact us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className="my-4">Contact us</h2>
      <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3070.10978523504!2d90.39754217319148!3d23.783142514675657!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c76cf7ff1085%3A0xc7380491877aaf8b!2zU2VjdG9yIGNvcnBvcmF0aW9uIEhvdXNpbmcgY29tcGxleCwgMDIg4Kaw4KeL4KahIOCmqOCmgiDgp6gsIOCmouCmvuCmleCmviAxMjEy!5e0!3m2!1sbn!2sbd!4v1668578487219!5m2!1sbn!2sbd"
        width="100%"
        height="400"
        title="map"
        style={{ border: 0 }}
        allowFullScreen={true}
        referrerPolicy="no-referrer-when-downgrade"
      ></iframe>

      <form className="form-group col-md-6 offset-md-3 my-4">
        <input
          type="text"
          className="form-control my-2"
          placeholder="Name"
          autoComplete="off"
          required
        />
        <input
          type="text"
          className="form-control my-2"
          placeholder="E-mail"
          autoComplete="off"
          required
        />
        <textarea
          name="Message"
          placeholder="Your Message"
          className="form-control"
          cols={20}
          rows={8}
          autoComplete="off"
          required
        ></textarea>
        <input
          type="submit"
          value="Send Message"
          className="btn res-nav-btn mt-3"
        />
      </form>
    </section>
  );
};

export default Contact;
