import { GetServerSideProps } from "next";
import Head from "next/head";
import { fetArticles, fetchCategories } from "../http";
import { AxiosResponse } from "axios";
import { Category, CollectionTypes, Article } from "../types";
import Categories from "../components/Categories";
import Articles from "../components/Articles";
import qs from "qs";

interface propsType {
  categories: Category[];
  articles: Article[];
}
export default function Home({ categories, articles }: propsType) {
  console.log(articles);

  return (
    <div>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Categories categories={categories} />
      <Articles articles={articles} />
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const options = {
    populate: ["author.avatar"],
    sort: ["id:desc"],
  };
  const queryString = qs.stringify(options);

  const { data: cateogry }: AxiosResponse<CollectionTypes<Category[]>> =
    await fetchCategories();

  const { data: articles }: AxiosResponse<CollectionTypes<Article[]>> =
    await fetArticles(queryString);

  return {
    props: {
      categories: cateogry.data,
      articles: articles.data,
    },
  };
};
