import Head from "next/head";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello there</h1>
      </main>
    </div>
  );
}
