import axios from "axios";
import Head from "next/head";
import React, { useState } from "react";
import { API_URL } from "../config/config";
import { useDispatch } from "react-redux";
import { userInfo } from "../redux/userSlice";
import { setUserCookie, verifyUser } from "../config/auth";

const Login = () => {
  const [userData, setUserData] = useState({
    identifier: "",
    password: "",
  });
  const dispatch = useDispatch();

  const handleChange = (e: any) => {
    setUserData({ ...userData, [e.target.name]: e.target.value });
  };

  const handleLogin = async (e: any) => {
    e.preventDefault();
    const loginInfo = {
      identifier: userData.identifier,
      password: userData.password,
    };
    try {
      const login = await axios.post(`${API_URL}/api/auth/local`, loginInfo);
      setUserCookie(login.data);
      (await verifyUser()) && dispatch(userInfo(login.data));
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className="mx-auto login-comp my-5">
      <Head>
        <title>Next Blog | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h4 className="mb-3">Login</h4>
      <form onSubmit={handleLogin}>
        <div className="form-outline mb-4">
          <input
            type="email"
            placeholder="Your email"
            name="identifier"
            id="form2Example1"
            className="form-control"
            onChange={handleChange}
            value={userData.identifier}
          />
        </div>
        <div className="form-outline mb-4">
          <input
            type="password"
            name="password"
            placeholder="Password"
            id="form2Example2"
            className="form-control"
            onChange={handleChange}
            value={userData.password}
          />
        </div>

        <button type="submit" className="btn btn-paginate mb-4">
          Sign in
        </button>

        <div className="text-center">
          <p>
            Not a member? <a href="#!">Register</a>
          </p>
        </div>
      </form>
    </div>
  );
};

export default Login;
