import axios from "axios";
import Head from "next/head";
import React, { useState } from "react";
import { API_URL } from "../config/config";
import { useDispatch } from "react-redux";
import { userInfo } from "../redux/userSlice";

const Login = () => {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const dispatch = useDispatch();

  const handleLogin = async (e: any) => {
    e.preventDefault();
    const loginInfo = {
      identifier: username,
      password: password,
    };
    try {
      const login = await axios.post(`${API_URL}/api/auth/local`, loginInfo);
      dispatch(userInfo(login.data));
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <div className="mx-auto login-comp my-5">
      <Head>
        <title>Next Blog | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h4 className="mb-3">Login</h4>
      <form onSubmit={handleLogin}>
        <div className="form-outline mb-4">
          <input
            type="email"
            placeholder="Your email"
            id="form2Example1"
            className="form-control"
            onChange={(e) => setUsername(e.target.value)}
            value={username}
          />
        </div>
        <div className="form-outline mb-4">
          <input
            type="password"
            placeholder="Password"
            id="form2Example2"
            className="form-control"
            onChange={(e) => setPassword(e.target.value)}
            value={password}
          />
        </div>

        <button type="submit" className="btn btn-paginate mb-4">
          Sign in
        </button>

        <div className="text-center">
          <p>
            Not a member? <a href="#!">Register</a>
          </p>
        </div>
      </form>
    </div>
  );
};

export default Login;
