import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React, { useState } from "react";
import { getTokenFromServerCookie } from "../config/auth";
import { API_URL } from "../config/config";

const Profile = ({ data }: any) => {
  // console.log(data);
  const router = useRouter();
  const [edit, setEdit] = useState(false);
  const [imageData, setImageData] = useState<any>(null);
  const { firstName, lastName, username, email, avatar2 } = data;

  const handlePhotoEdit = () => {
    setEdit(true);
  };
  const handleImageSelect = (e: any) => {
    const tempImg = e.target.files[0];
    setImageData(tempImg);
  };
  const handleSave = async () => {
    const formData = new FormData();
    const file = imageData;
    formData.append("inputFile", file);
    formData.append("user_id", data.id);
    try {
      const response = await fetch("/api/upload", {
        method: "POST",
        body: formData,
      });
      const responseData = await response.json();
      console.log(responseData);
      if (responseData.message === "success") {
        router.reload();
      }
    } catch (error) {
      console.error(JSON.stringify(error));
    }
    setEdit(false);
  };
  return (
    <>
      <Head>
        <title>Next Blog | {firstName + " " + lastName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <div className="container py-5">
          <div className="row">
            <div className="col-lg-4">
              <div className="card mb-4">
                <div className="card-body text-center">
                  <div className="prof-img-div">
                    {data?.avatar2 === null ? (
                      <img
                        src="R.png"
                        alt="avatar"
                        className="img-fluid"
                        style={{ width: "150px" }}
                      />
                    ) : (
                      <Image
                        src={`https://res.cloudinary.com/dnqvwwxzv/image/upload/${avatar2}`}
                        alt="avatar"
                        height={100}
                        width={100}
                        className="img-fluid"
                      />
                    )}
                  </div>
                  <h5 className="my-3">{firstName + " " + lastName}</h5>
                  <p className="text-muted mb-1">@{username}</p>
                  <p className="text-muted mb-4">Bay Area, San Francisco, CA</p>
                  <div className="d-flex justify-content-center mb-2"></div>
                </div>
              </div>
              <div className=" mb-4 mb-lg-0">
                {/* <div className="card-body p-0">
                  <ul className="list-group list-group-flush rounded-3">
                    <li className="list-group-item d-flex justify-content-between align-items-center p-3">
                      <i className="fas fa-globe fa-lg text-warning"></i>
                      <p className="mb-0">https://www.nextblog.com</p>
                    </li>
                  </ul>
                </div> */}
                {edit ? (
                  <div className="">
                    <label className="form-label" htmlFor="customFile">
                      Choose a photo to upload
                    </label>
                    <input
                      type="file"
                      className="form-control"
                      id="customFile"
                      onChange={handleImageSelect}
                    />
                    <button
                      className="btn res-nav-btn mt-3"
                      type="submit"
                      onClick={handleSave}
                    >
                      Save
                    </button>
                  </div>
                ) : (
                  <button className="btn res-nav-btn" onClick={handlePhotoEdit}>
                    Edit profile
                  </button>
                )}
              </div>
            </div>
            <div className="col-lg-8">
              <div className="card mb-4">
                <div className="card-body">
                  <div className="row">
                    <div className="col-sm-3">
                      <p className="mb-0">Full Name</p>
                    </div>
                    <div className="col-sm-9">
                      <p className="text-muted mb-0">
                        {firstName + " " + lastName}
                      </p>
                    </div>
                  </div>
                  <hr />
                  <div className="row">
                    <div className="col-sm-3">
                      <p className="mb-0">Email</p>
                    </div>
                    <div className="col-sm-9">
                      <p className="text-muted mb-0">{email}</p>
                    </div>
                  </div>
                  <hr />
                  <div className="row">
                    <div className="col-sm-3">
                      <p className="mb-0">Phone</p>
                    </div>
                    <div className="col-sm-9">
                      <p className="text-muted mb-0"></p>
                    </div>
                  </div>
                  <hr />
                  <div className="row">
                    <div className="col-sm-3">
                      <p className="mb-0">Mobile</p>
                    </div>
                    <div className="col-sm-9">
                      <p className="text-muted mb-0"></p>
                    </div>
                  </div>
                  <hr />
                  <div className="row">
                    <div className="col-sm-3">
                      <p className="mb-0">Address</p>
                    </div>
                    <div className="col-sm-9">
                      <p className="text-muted mb-0"></p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="row">
                <div className="col-md-6">
                  <div className="card mb-4 mb-md-0">
                    <div className="card-body">
                      <p className="mb-4">
                        <span className="text-primary font-italic me-1">
                          assigment
                        </span>{" "}
                        Project Status
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-md-6">
                  <div className="card mb-4 mb-md-0">
                    <div className="card-body">
                      <p className="mb-4">
                        <span className="text-primary font-italic me-1">
                          assigment
                        </span>{" "}
                        Project Status
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Profile;

export const getServerSideProps = async ({ req }: any) => {
  const serverJwt = getTokenFromServerCookie(req);
  if (!serverJwt) {
    return {
      redirect: {
        destination: "/login",
      },
    };
  }
  if (serverJwt) {
    const res = await fetch(`${API_URL}/api/users/me`, {
      headers: {
        Authorization: `Bearer ${serverJwt}`,
      },
    });
    const verifiedUser = await res.json();
    return {
      props: {
        data: verifiedUser,
      },
    };
  } else {
    return {
      props: { data: "error" },
    };
  }
};
